name: Publish Blocks

on:
  # pull_request:
  #   branches: [ develop ]
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build all
        run: yarn build

      - name: 🗃 Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist


      # - name: Upload blocks-cdn.lowdefy.com/blocks-aggrid
      #   run: |
      #     aws --region eu-west-1 s3 sync dist s3://blocks-cdn.lowdefy.com/${{ github.event.release.tag_name }}/blocks-aggrid --acl public-read --cache-control 'public, max-age=31536000'
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_BLOCKS_CDN_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_BLOCKS_CDN_SECRET_ACCESS_KEY }}
